
modLoader="javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId="manacrystals"
version="1.0.5"
displayName="Mana Crystals"
authors="gobies"
description='''A way to increase max mana permanently in Minecraft!'''

[[dependencies.manacrystals]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.manacrystals]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side= "BOTH"

[modproperties.manacrystals]
configuredBackground="minecraft:textures/block/stone_bricks.png"
